### ISSUE TITLE
interesting project: few questions :)

### ISSUE THREAD

**Issue by chicco785** [3scale/authorino#6]
this looks look really like an interesting project, i have a couple of questions:

1) will the project be integrated at any level with 3scale API management? (I suppose that that's the idea, given that is in the 3 scale repo :) )

2) the description states:

> It's important to notice that Authorino does NOT manage resources in the UMA-compliant server. As shown in the flow above, Authorino's UMA client is only to fetch data about the requested resources. Authorino exchanges client credentials for a Protected API Token (PAT), then queries for resources whose URI match the path of the HTTP request (as passed to Authorino by the Envoy proxy) and fecthes data of each macthing resource.

How then resource creation will be handled? Suppose that making a post on /pippo you create a resource of type pippo, if there is not "automatic" registration of the new resource on the UMA api, this will have to be handled manually. Right?

**Comment by guicassolato** [comment]
Hello, @chicco785. Thank you for your interest in Authorino!

I'll try to address your two questions...

> 1. will the project be integrated at any level with 3scale API management? (I suppose that that's the idea, given that is in the 3 scale repo :) )

Authorino is one of the candidates for becoming the _de facto_ authentication/authorization components of the next generation of 3scale, but it will also have independent life, presenting itself as a generic auth broker regardless of other typical API management features (rate limiting, monetization, account management, developer portal, etc).

A little heads-up: we will be moving Authorino together with several other 3scale projects into https://github.com/3scale-labs.

> 2. the description states:
> 
> > It's important to notice that Authorino does NOT manage resources in the UMA-compliant server. As shown in the flow above, Authorino's UMA client is only to fetch data about the requested resources. Authorino exchanges client credentials for a Protected API Token (PAT), then queries for resources whose URI match the path of the HTTP request (as passed to Authorino by the Envoy proxy) and fecthes data of each macthing resource.
> 
> How then resource creation will be handled? Suppose that making a post on /pippo you create a resource of type pippo, if there is not "automatic" registration of the new resource on the UMA api, this will have to be handled manually. Right?

UMA implementation is far from complete in Authorino yet and your question is absolutely relevant. The short answer is: we don't know yet. The original plan is for Authorino NOT to handle resource registration at all, and leave that entirely for the resource server. This design implies that the authorization rules would have to allow POST requests for the creation of resources by other/additional criteria (e.g. RBAC) and the resource server would have to handle the registration manually, as you said yourself. However, things can also evolve differently.

Right now we are mostly focused on proving that Authorino is viable as a concept, evaluating the technologies and industry standards. If the UMA-client implementation really thrives into the final design of Authorino, that whole very simple path/uri resource querying that Authorino currently supports is definitely one of the things to be enhanced and then also a good time to decide on the resource creation issue.

Thank you again for opening this issue thus helping us to enrich the open source dialogue.
